version: '3.6'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 111115
      MYSQL_DATABASE: rbserver
      MYSQL_USER: ROOT
      MYSQL_PASSWORD: 111115
    volumes:
      - /rbserver.sql:/var/lib/mysql
    ports:
      - "3307:3306"




  back:
    build:
     context: ./backend
     dockerfile: Dockerfile
    restart: unless-stopped
    ports:
    - 8080:8080

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5173:80
